"""Extract apple-1 boundary landmarks for the SST widgets.

Replicates TDA-SST's segmentation convention (skimage marching-squares contour
at level 0.5, largest closed boundary, arc-length reparametrization), then
centres and scale-normalizes to a canonical size and emits a JS module the
widgets import.

Run (website repo root, venv active; needs numpy + scikit-image):
    USERPROFILE="$USERPROFILE" ~/venvs/zgrey-github-io/Scripts/python.exe scripts/extract_apple.py

Source image: TDA-SST/data/MPEG7/apples/apple-1.png (MPEG-7 shape dataset).
Outputs:
    src/assets/js/sst/widgets/_apple.js     (landmark array, the deliverable)
    scripts/apple_preview.png               (sanity-check render, not committed)
"""

from pathlib import Path
import numpy as np
from skimage import io
from skimage.measure import find_contours

N = 72  # landmarks (arc-length uniform)

SRC = Path.home() / "Git/GitHub/TDA-SST/data/MPEG7/apples/apple-1.png"
OUT_JS = Path(__file__).resolve().parent.parent / "src/assets/js/sst/widgets/_apple.js"
OUT_PNG = Path(__file__).resolve().parent / "apple_preview.png"


def arclen(c):
    return float(np.sum(np.linalg.norm(np.diff(c, axis=0), axis=1)))


def main():
    img = io.imread(str(SRC), as_gray=True)
    bw = (img > 0.5).astype(float)            # white silhouette -> 1
    contours = find_contours(bw, 0.5)
    if not contours:
        raise RuntimeError("no contour found")
    c = max(contours, key=arclen)             # outer apple boundary (row, col)

    # image (row, col) -> (x, y) with y up
    H = bw.shape[0]
    xy = np.column_stack([c[:, 1], H - c[:, 0]])

    # drop a duplicate closing vertex if present, then arc-length resample
    if np.allclose(xy[0], xy[-1]):
        xy = xy[:-1]
    d = np.linalg.norm(np.diff(xy, axis=0, append=xy[:1]), axis=1)
    s = np.concatenate([[0.0], np.cumsum(d)])
    L = s[-1]
    snew = np.linspace(0.0, L, N, endpoint=False)
    # interpolate on the closed curve (wrap by appending the first point)
    xs = np.interp(snew, s, np.append(xy[:, 0], xy[0, 0]))
    ys = np.interp(snew, s, np.append(xy[:, 1], xy[0, 1]))
    P = np.column_stack([xs, ys])

    # centre, and scale so RMS radius = 1 (stable canonical size)
    P -= P.mean(axis=0)
    rms = np.sqrt(np.mean(np.sum(P * P, axis=1)))
    P /= rms

    bbox = (P[:, 0].min(), P[:, 0].max(), P[:, 1].min(), P[:, 1].max())
    print(f"landmarks: {len(P)}  bbox x[{bbox[0]:.2f},{bbox[1]:.2f}] "
          f"y[{bbox[2]:.2f},{bbox[3]:.2f}]")

    # preview
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(3, 3))
        cp = np.vstack([P, P[:1]])
        ax.plot(cp[:, 0], cp[:, 1], "-o", ms=3, color="#537949")
        ax.plot(P[0, 0], P[0, 1], "o", color="#c9603f")  # start landmark
        ax.set_aspect("equal"); ax.axis("off")
        fig.savefig(OUT_PNG, dpi=110, bbox_inches="tight")
        print(f"preview -> {OUT_PNG}")
    except Exception as e:  # noqa: BLE001
        print(f"(preview skipped: {e})")

    # emit JS
    rows = ",\n  ".join(f"[{x:.4f}, {y:.4f}]" for x, y in P)
    js = (
        "/**\n"
        " * Apple-1 boundary landmarks (MPEG-7 shape dataset).\n"
        " *\n"
        " * Generated by scripts/extract_apple.py from\n"
        " * TDA-SST/data/MPEG7/apples/apple-1.png via skimage find_contours\n"
        " * (level 0.5), largest boundary, arc-length reparametrized to "
        f"{N} landmarks,\n"
        " * centred, RMS-radius normalized to 1. y is up; the stem points +y.\n"
        " * Regenerate: python scripts/extract_apple.py\n"
        " */\n\n"
        f"export const APPLE = [\n  {rows}\n];\n"
    )
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"wrote {OUT_JS}  ({len(P)} landmarks)")


if __name__ == "__main__":
    main()
